<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="A2ML30049" name="io.mosip.authentication.tests.InternalBiometricAuthentication" tests="3" failures="0" timestamp="26 Jul 2019 06:31:58 GMT" time="22.038" errors="3">
  <testcase name="InternalAuthentication_Biometric_Iris_With_Valid_Smoke_Pos" time="4.362" classname="io.mosip.authentication.tests.InternalBiometricAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
at io.mosip.authentication.tests.InternalBiometricAuthentication.internalBiometricAuthenticationTest(InternalBiometricAuthentication.java:203)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:46)
at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:12)
at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:17)
]]>
    </error>
  </testcase> <!-- InternalAuthentication_Biometric_Iris_With_Valid_Smoke_Pos -->
  <testcase name="InternalAuthentication_Biometric_Face_With_Valid_Smoke_Pos" time="12.583" classname="io.mosip.authentication.tests.InternalBiometricAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
at io.mosip.authentication.tests.InternalBiometricAuthentication.internalBiometricAuthenticationTest(InternalBiometricAuthentication.java:203)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:46)
at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:12)
at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:17)
]]>
    </error>
  </testcase> <!-- InternalAuthentication_Biometric_Face_With_Valid_Smoke_Pos -->
  <testcase name="InternalAuthentication_Biometric_Finger_With_Valid_Smoke_Pos" time="5.093" classname="io.mosip.authentication.tests.InternalBiometricAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
at io.mosip.authentication.tests.InternalBiometricAuthentication.internalBiometricAuthenticationTest(InternalBiometricAuthentication.java:203)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:46)
at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:12)
at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:17)
]]>
    </error>
  </testcase> <!-- InternalAuthentication_Biometric_Finger_With_Valid_Smoke_Pos -->
</testsuite> <!-- io.mosip.authentication.tests.InternalBiometricAuthentication -->
