<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="A2ML30049" ignored="0" name="EmailNotificationServiceTest" tests="5" failures="5" timestamp="26 Jul 2019 10:34:08 GMT" time="77.224" errors="0">
  <testcase name="validatePacketCreation" time="6.084" classname="io.mosip.registration.main.PacketCreation">
    <failure type="java.lang.AssertionError" message="expected [Success] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [Success] but found [null]
at io.mosip.registration.util.CommonUtil.verifyAssertionResponse(CommonUtil.java:849)
at io.mosip.registration.main.PacketCreation.validatePacketCreation(PacketCreation.java:181)
at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:180)
at io.mosip.registration.main.RegClient.createPacket(RegClient.java:25)
at io.mosip.e2e.tests.PacketGeneratorTest.generateValidInvalidPackets(PacketGeneratorTest.java:60)
at io.mosip.e2e.runner.EndToEndRun.main(EndToEndRun.java:29)
... Removed 52 stack frames]]>
    </failure>
  </testcase> <!-- validatePacketCreation -->
  <testcase name="validatePacketCreation" time="1.675" classname="io.mosip.registration.main.PacketCreation">
    <failure type="java.lang.AssertionError" message="expected [Success] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [Success] but found [null]
at io.mosip.registration.util.CommonUtil.verifyAssertionResponse(CommonUtil.java:849)
at io.mosip.registration.main.PacketCreation.validatePacketCreation(PacketCreation.java:181)
at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:180)
at io.mosip.registration.main.RegClient.createPacket(RegClient.java:25)
at io.mosip.e2e.tests.PacketGeneratorTest.generateValidInvalidPackets(PacketGeneratorTest.java:60)
at io.mosip.e2e.runner.EndToEndRun.main(EndToEndRun.java:29)
... Removed 52 stack frames]]>
    </failure>
  </testcase> <!-- validatePacketCreation -->
  <testcase name="validatePacketCreation" time="1.822" classname="io.mosip.registration.main.PacketCreation">
    <failure type="java.lang.AssertionError" message="expected [Success] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [Success] but found [null]
at io.mosip.registration.util.CommonUtil.verifyAssertionResponse(CommonUtil.java:849)
at io.mosip.registration.main.PacketCreation.validatePacketCreation(PacketCreation.java:181)
at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:180)
at io.mosip.registration.main.RegClient.createPacket(RegClient.java:25)
at io.mosip.e2e.tests.PacketGeneratorTest.generateValidInvalidPackets(PacketGeneratorTest.java:60)
at io.mosip.e2e.runner.EndToEndRun.main(EndToEndRun.java:29)
... Removed 52 stack frames]]>
    </failure>
  </testcase> <!-- validatePacketCreation -->
  <testcase name="validatePacketCreation" time="0.74" classname="io.mosip.registration.main.PacketCreation">
    <failure type="java.lang.AssertionError" message="expected [Success] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [Success] but found [null]
at io.mosip.registration.util.CommonUtil.verifyAssertionResponse(CommonUtil.java:849)
at io.mosip.registration.main.PacketCreation.validatePacketCreation(PacketCreation.java:181)
at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:180)
at io.mosip.registration.main.RegClient.createPacket(RegClient.java:25)
at io.mosip.e2e.tests.PacketGeneratorTest.generateValidInvalidPackets(PacketGeneratorTest.java:60)
at io.mosip.e2e.runner.EndToEndRun.main(EndToEndRun.java:29)
... Removed 52 stack frames]]>
    </failure>
  </testcase> <!-- validatePacketCreation -->
  <testcase name="validatePacketCreation" time="3.579" classname="io.mosip.registration.main.PacketCreation">
    <failure type="java.lang.AssertionError" message="expected [Success] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [Success] but found [null]
at io.mosip.registration.util.CommonUtil.verifyAssertionResponse(CommonUtil.java:849)
at io.mosip.registration.main.PacketCreation.validatePacketCreation(PacketCreation.java:181)
at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:180)
at io.mosip.registration.main.RegClient.createPacket(RegClient.java:25)
at io.mosip.e2e.tests.PacketGeneratorTest.generateValidInvalidPackets(PacketGeneratorTest.java:60)
at io.mosip.e2e.runner.EndToEndRun.main(EndToEndRun.java:29)
... Removed 52 stack frames]]>
    </failure>
  </testcase> <!-- validatePacketCreation -->
</testsuite> <!-- EmailNotificationServiceTest -->
